name: "Build"

on:
  workflow_dispatch:
    inputs:
      arg_name:
        description: "Arguments Options"
        required: true
        default: tkR
jobs:
  building:
    runs-on: ubuntu-26.04
    steps:
         - uses: actions/checkout@v4
    
         - run: export WP="$(realpath $PWD/../)"; bash build/ckbuild_actions.sh -${{ github.event.inputs.arg_name }}
    
         - name: Upload Aosp Clang
           uses: actions/upload-artifact@v4
           with:
            name: aosp-$ZIP_PATH
            path: $ZIP_PATH

         - run: export WP="$(realpath $PWD/../)"; bash build/ckbuild_actions.sh -${{ github.event.inputs.arg_name }} -n

         - name: Upload Neutron Clang
           uses: actions/upload-artifact@v4
           with:
            name: neutron-$ZIP_PATH
            path: $ZIP_PATH
