name: "Build"

on:
  workflow_dispatch:
    inputs:
      arg_name:
        description: "Arguments Options"
        required: true
        default: tkR
jobs:
  build:
    runs-on: ubuntu-26.04
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - clang: aosp
            branch: Lima
          - clang: neutron
            branch: Lima

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ matrix.branch }}
        fetch-depth: 0
        submodules: recursive
        
    - name: Update apt
      run: sudo apt-get update
      
    - name: Install dependencies
      run: |
        sudo apt-get install -y \
          build-essential openjdk-8-jdk maven cmake byacc flex automake libtool-bin \
          bison binutils-dev libiberty-dev zip unzip libncurses5-dev curl git ninja-build \
          python3 libssl-dev gcc-aarch64-linux-gnu cpio gawk libarchive-tools lz4 repo

    - name: Set clang flags for variant
      id: vars
      run: |
        if [ "${{ matrix.clang }}" = "neutron" ]; then
          echo "FLAGS=n" >> $GITHUB_OUTPUT
          echo "Using Neutron Clang"
        else
          echo "FLAGS=-" >> $GITHUB_OUTPUT
        fi

    - name: Run kernel build
      run: export WP="$(realpath $PWD/../)"; bash build/ckbuild.sh -${{ steps.vars.outputs.FLAGS }}${{ github.event.inputs.arg_name }}
    
    - name: Upload Kernel
      uses: actions/upload-artifact@v4
      with:
        name: $ZIP_PATH
        path: $ZIP_PATH
